### ISSUE TITLE
what is the meaning of seman_map, which was defined at calc_gt_center()?

### ISSUE THREAD

**Issue by msha096** [liuwei16/CSP#46]
Hi, thanks for sharing the code.

I have a question about seman_map, defined at calc_gt_center().
It seems to be used to classify the foreground or background. Could anyone further explain the meaning and usage of that? What is the intuition behind that? Why use the Gaussian function?

Thanks!

**Comment by dominikandreas** [comment]
I'm not sure what "seman" is supposed to mean, but it's sort of a probability map for "centerness", i.e. the probability that a pixel belongs to a center (called "Gaussian Mask" or "Center Heatmap" in the paper). It's used to adapt the classification loss such that misclassifications for pixels that have a high centerness probability are down-weighted. the Gaussian is used because it allows to define the probability in terms of vertical and horizontal offset from the ground truth center, whereas the variance is scaled with the width and height of the object. For more information, take a look at equation 4 in the paper:
http://openaccess.thecvf.com/content_CVPR_2019/papers/Liu_High-Level_Semantic_Feature_Detection_A_New_Perspective_for_Pedestrian_Detection_CVPR_2019_paper.pdf
